# Generated by Django 5.1.6 on 2025-03-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('reviewer', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('role', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
