# Generated by Django 5.1.7 on 2025-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhub', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
