# Generated by Django 5.1.7 on 2025-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhub', '0003_contractorofthemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
