# Generated by Django 5.1.7 on 2025-04-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhub', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='reviewer_name',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
